### PR TITLE
Update Nitro docs

### PR DESCRIPTION
**Pull request by hahuyhoang411**
- [x] Update Community docs
- [x] Update API
- [x] Update Examples (Gradio UI)
- [x] ... more

### CODE REVIEW

**Comment by dan-jan** [comment]
@hahuyhoang Quick feedback on the WIP Nitro Docs: 

**URL Structure**
- https://nitro.jan.ai/docs/... should be the URL for docs
- Avoid https://nitro.jan.ai/nitro (redundant, bad for SEO, etc)

****

**Documentation Structure**
- I would recommend a clearer structure for Docs

```
- Overview (docs root, i.e.http://nitro.jan.ai/docs)
   - What is Nitro?
   - Features
   - Acknowledgements
- Architecture (1 page)
    - Architecture
    - Key Concepts
- Getting Started (1 page)
   - Installation
   - ? (npm, pip etc)
   - Your first Inference Request
- Using Nitro
   - Using Zephyr with Nitro
- Examples
    - Gradio app with Nitro
```

**API Reference**
- Should Nitro have an OpenAPI Swagger defintion? (i.e. curl requests)
- `/chat_completion`
- `/embeddings`?

**Branding**
- [ ] Icon for site should show Nitro lightning (vs. Jan)
image

**Comment by hahuyhoang411** [comment]
Crystallized the documentation for now. Please pull and comment on the latest one.

**Comment by hahuyhoang411** [comment]
Updated the API Reference for Nitro

**Comment by hahuyhoang411** [comment]
Please look through and merge it for a website launch.

**Review by tikikun — APPROVED** [review]
approved, no code changes detected

**Pull request merged**
